sudo: required

services:
  - docker

before_install:
  - curl -fsSL get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
  - sudo apt-get update
  - sudo apt-get -y install build-essential
  - sudo usermod -aG docker $USER
  - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

script:
  - sudo make bdd
