version: '3'

services:
  oauth:
    build: .
    command: npm start
    links:
      - rabbit
      - mysql
    environment:
      - NODE_ENV=production
      - RABBITMQ_URL=amqp://rabbit
      - MYSQL_HOST=mysql
      - MYSQL_USER=cerbero
      - MYSQL_PASSWORD=cerbero
      - MYSQL_DATABASE=cerbero
    command: sh -c './wait-for-it.sh rabbit:5672 -- npm run test:bdd'
  rabbit:
    image: rabbitmq:alpine
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=cerbero
      - MYSQL_PASSWORD=cerbero
      - MYSQL_DATABASE=cerbero
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    labels:
      traefik.enable: "false"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci